version: '{build}'

os: Visual Studio 2013

init:
  - git config --global core.autocrlf true


install:
# Workaround for NUnit Console Runner v3.2.1 timeout bug (#1509). Try to remove it when a fix is available.
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/nunit-3-2-0.ps1'))
# Workaround, as FireFox 47 crashes on Selenium test startup. Wait until stable FireFox is out.
- choco install firefox -version 46.0.1
  
cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

build:
  project: AjaxControlToolkit.sln
  publish_wap: true
  verbosity: minimal

test:
  assemblies: bin\AjaxControlToolkit.Tests.dll
 
services: iis
 
before_test:
- ps: "& \"C:\\Program Files\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe\" -verb:sync -source:iisApp=\"$env:APPVEYOR_BUILD_FOLDER\\AjaxControlToolkit.Jasmine\" -dest:iisApp=`\"Default Web Site`\"\n\n\n$FilesAndFolders = gci \"C:\\inetpub\\wwwroot\" -recurse | % {$_.FullName}\nforeach($FileAndFolder in $FilesAndFolders)\n{\n    $item = gi -literalpath $FileAndFolder \n    $acl = $item.GetAccessControl() \n    $permission = \"Everyone\",\"FullControl\",\"Allow\"\n    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule $permission\n    $acl.SetAccessRule($rule)\n    $item.SetAccessControl($acl)\n}"