version: '{build}'

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

build:
  project: AjaxControlToolkit.sln
  verbosity: minimal

test:
  assemblies: bin\AjaxControlToolkit.Tests.dll